version: '2'
services:
  web:
    image: web
    build:
      context: .
      dockerfile: ./.docker/stage/apache/Dockerfile
    environment:
      - DB_NAME=
      - DB_USER=
      - DB_PASSWORD=
      - DB_HOST=
      - DB_PREFIX=wp_
      - WP_HOME=http://something.stage.example.com
      - WP_DEBUG=1
      - WP_SITEURL=http://something.stage.example.com/cms
    ports:
      - "80:80"
      - "443:443"
    networks:
      - staging-net
networks:
  staging-net:
    external: true
