version: '2'
services:
  wp.apache:
    image: projectname.com:latest
    build:
      context: ../../
      dockerfile: .docker/local/apache/Dockerfile
    env_file:
      - ./local.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../:/var/www/html
      - ./apache/public/.htaccess:/var/www/html/public/.htaccess
      - ./apache/sites-available:/etc/apache2/sites-available
      - ./apache/sites-available:/etc/apache2/sites-enabled
      - ../../plugins:/var/www/html/public/wp-content/mu-plugins
      - ../../theme:/var/www/html/public/wp-content/themes/boilerplate
      - ../../storage/plugins:/var/www/html/public/wp-content/plugins
      - ../../storage/uploads:/var/www/html/public/wp-content/uploads
      - ../../bootstrap:/var/www/html/public/wp-content/mu-plugins/bootstrap
      - ../../vendor:/var/www/html/public/wp-content/mu-plugins/bootstrap/vendor
      - ../../app:/var/www/html/public/wp-content/mu-plugins/bootstrap/app
      - ../../packages:/var/www/html/public/wp-content/mu-plugins/bootstrap/packages
      - ../../wp-config.php:/var/www/html/wp-config.php
  wp.email:
    image: modularitycontainers/postfix
    environment:
      - MYHOSTNAME=localhost
    volumes:
      - ./email/postfix:/var/spool/postfix
      - ./email/mail:/var/spool/mail
  wp.mysql:
    image: mysql
    environment:
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
  app.storage:
    image: minio/minio
    environment:
       MINIO_ACCESS_KEY: 58XG458BLCZIQ72UZYKY
       MINIO_SECRET_KEY: nMrbLbRA6aGsDhA0gb40kRCe6n4uaoPzXGzxfFRa
    command: server /export
    volumes:
      - ./storage/data:/export
    ports:
      - "9000:9000"