version: '2'
services:
  wp.apache:
    image: wpdockerlocal/web
    build:
      context: ../../
      dockerfile: .docker/local/apache/Dockerfile
    environment:
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=secret
      - DB_HOST=wp.mysql
      - WP_PREFIX=wp_
      - WP_HOME=http://localhost
      - WP_DEBUG=1
      - WP_SITEURL=http://localhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../:/var/www/html
      - ./apache/public/.htaccess:/var/www/html/public/.htaccess
      - ./apache/sites-available:/etc/apache2/sites-available
      - ./apache/sites-enabled:/etc/apache2/sites-enabled
      - ../../plugins:/var/www/html/public/wp-content/mu-plugins
      - ../../theme:/var/www/html/public/wp-content/themes/boilerplate
      - ../../storage/plugins:/var/www/html/public/wp-content/plugins
      - ../../storage/uploads:/var/www/html/public/wp-content/uploads
      - ../../bootstrap:/var/www/html/public/wp-content/mu-plugins/bootstrap
      - ../../vendor:/var/www/html/public/wp-content/mu-plugins/bootstrap/vendor
      - ../../app:/var/www/html/public/wp-content/mu-plugins/bootstrap/app
      - ../../config.php:/var/www/html/public/wp-config.php
      - ../../.env:/var/www/html/public/.env
  wp.mysql:
    image: mysql
    environment:
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
